# Generated by Django 4.1.4 on 2022-12-19 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virRPG', '0004_alter_character_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attack',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='campaing_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
